shallow_clone: true

os: Visual Studio 2015

  
configuration:
  - debug
  - release

platform: x64

build:
  verbosity: detailed

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest -R --output-on-failure
