
shallow_clone: true

os:
  - Visual Studio 2015

build:
  verbosity: detailed

configuration:
  - Debug

branches:
  except:
    - /pr\/.+/


install:
  ############################################################################
  # All external dependencies are installed in C:\projects\deps
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  ############################################################################
  # Install Ninja
  ############################################################################
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version
  
    ############################################################################
  # Install a recent CMake
  ############################################################################
  - set CMAKE_URL="https://cmake.org/files/v3.4/cmake-3.4.0-win32-x86.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps\cmake > nul
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

  ############################################################################
  # Setup the path to Clang-cl
  ############################################################################
  - set PATH="C:\Program Files\LLVM\bin";%PATH%
  - clang-cl -v

  ############################################################################
  # Install gtest
  ############################################################################
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - set GTEST_URL="https://github.com/google/googletest/archive/release-1.8.0.zip"
  - appveyor DownloadFile %GTEST_URL% -FileName gtest.zip
  - 7z x gtest.zip -oC:\projects\deps\gtest > nul
  - cd C:\projects\deps\gtest\googletest-release-1.8.0
  - ls
  - mkdir build && cd build
  - cmake .. -GNinja -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_CXX_FLAGS="-fms-compatibility-version=19 -Wno-deprecated-declarations" 
  - cmake --build .
  - ls
  - ls C:\projects\deps\gtest\googletest-release-1.8.0\googletest\include\gtest
  - set PATH=%PATH%;C:\projects\deps\gtest\googletest-release-1.8.0\build\googlemock\gtest;C:\projects\deps\gtest\googletest-release-1.8.0\googletest\include\gtest

before_build:
  - cd C:\projects\fung

build_script:
  - mkdir build
  - cd build
  - cmake .. -GNinja -DGTEST_INCLUDE_DIR="C:\projects\deps\gtest\googletest-release-1.8.0\googletest\include\gtest" -DCMAKE_PREFIX_PATH="C:\projects\deps\gtest\googletest-release-1.8.0" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_CXX_FLAGS="-fms-compatibility-version=19"
  - ninja && ctest -R --output-on-failure
