shallow_clone: true

os:
  - Visual Studio 2015 Update 2
  
configuration:
  - debug
  - release

environment:
  - platform: x64

build:
  verbosity: detailed

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest -R --output-on-failure
