language: cpp
compiler: gcc
before_install:
- "$CXX --version"
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -qq g++-4.9
- export CXX="g++-4.9" CC="gcc-4.9"
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
- hg clone https://bitbucket.org/eigen/eigen/
install:
- sudo pip install cpp-coveralls
script:
- "$CXX --version"
- mkdir build
- cd build
- cmake ..
- make
- "./unit_tests"
after_success:
- coveralls --root .. --exclude eigen --exclude build/CMakeFiles/CompilerIdC --exclude build/CMakeFiles/CompilerIdCXX --exclude FunG/Tests --exclude test --exclude external --gcov 'gcov-4.9' --gcov-options '\-lp'
- sudo apt-get install --yes doxygen graphviz
