language: cpp

compiler:
  - gcc 
  
before_install:
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"
  - sudo pip install cpp-coveralls
  
script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./unit_tests
  
after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"
