os: linux
dist: focal
language: python
python: "3.7"

addons:
  apt:
    packages:
    - g++-10
    - gcc-10
    - clang-9
    - ruby2.7
    - libopenblas-dev
    - liblapack-dev
    - lcov
    - cmake
    - libeigen3-dev
    - libdune-common-dev

matrix:
  include:
    # LINUX
    # GCC 10
    - os: linux
      env: CC=gcc-10 CXX=g++-10 COMPILER=gcc VERSION=10 COMPUTE_COVERAGE=true
      compiler: gcc
    # LINUX
    # CLANG 9
    - os: linux
      env: CC=clang-9 CXX=clang++-9 COMPILER=clang VERSION=9 COMPUTE_COVERAGE=false
      compiler: clang
     
install:
  - pip install conan
  - sudo gem install coveralls-lcov

script:
  - mkdir build && cd build
  - conan install .. --build missing -s compiler=${COMPILER} -s compiler.version=${VERSION} -s compiler.libcxx=libstdc++11
  - |
    if [[ "${COMPUTE_COVERAGE}" == "true" ]]; then
      cmake .. -DBuildTest=ON -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-coverage"
    else
      cmake .. -DBuildTest=ON -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake
    fi
  - cmake --build .
  - cd test && ctest

after_success:
  ############################################################################
  # Upload coverage information to coveralls.io
  ############################################################################
  - |
    if [[ "${COMPUTE_COVERAGE}" == "true" ]]; then
      lcov --gcov-tool gcov-10 --capture --no-external --directory . --base-directory ${TRAVIS_BUILD_DIR}/include -rc lcov_branch_coverage=1 --output-file coverage.info
      coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
    fi
  ############################################################################
  # Upload documentation to repository
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${MAKE_DOC}" == "true" ]]; then
      cd $TRAVIS_BUILD_DIR/build
      make doc
      ../deploy_doc.sh
    fi

