language: cpp
compiler: gcc
before_install:
- IGNORE_COVERAGE='*/external/* */test/*'
- openssl aes-256-cbc -K $encrypted_25dce5acf934_key -iv $encrypted_25dce5acf934_iv
  -in config/travisci_rsa.enc -out config/travisci_rsa -d
- chmod 0600 config/travisci_rsa
- cp config/travisci_rsa ~/.ssh/id_rsa
- "$CXX --version"
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -qq g++-4.9
- export CXX="g++-4.9" CC="gcc-4.9"
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
install:
- sudo pip install cpp-coveralls
script:
- "$CXX --version"
- mkdir build
- cd build
- cmake ..
- make
- "./unit_tests"
after_success:
- mkdir -p coveralls
- find -name "*.gcda" -exec cp "{}" coveralls/ \;
- find -name "*.gcno" -exec cp "{}" coveralls/ \;
- sudo apt-get install -qq python-yaml lcov
- lcov --directory coveralls --base-directory ./ --capture --output-file coveralls/coverage.info
- lcov --remove coveralls/coverage.info "*/test/*" $IGNORE_COVERAGE "*/Examples/*"  -o coveralls/coverage.info
- OTHER_LIBS=`grep "submodule .*" .gitmodules | sed 's/\[submodule\ "\(.*\)"\]/"\*\/boost\/\1\.hpp" "\*\/boost\/\1\/\*"/g'| sed "/\"\*\/boost\/$PROJECT_TO_TEST\/\*\"/d" | sed ':a;N;$!ba;s/\n/ /g'`
- echo $OTHER_LIBS
- eval "lcov --remove $PROJECT_DIR/coverals/coverage.info $OTHER_LIBS -o $PROJECT_DIR/coverals/coverage.info"
- gem install coveralls-lcov
- coveralls-lcov coveralls/coverage.info
- sudo apt-get install --yes doxygen graphviz
- cd ..
- "./config/publish-doc"
