macro(add_funcy_header header)
    list(APPEND HEADER_FILES $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/fung/${header}>)
endmacro(add_funcy_header)

macro(add_texy_header header)
    list(APPEND HEADER_FILES $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/texy/${header}>)
endmacro(add_texy_header)

macro(add_stringy_header header)
    list(APPEND HEADER_FILES $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/stringy/${header}>)
endmacro(add_stringy_header)

macro(add_header header)
    add_funcy_header(${header})
    add_texy_header(${header})
    add_stringy_header(${header})
endmacro(add_header)

macro(tmp_add_header header)
    add_funcy_header(${header})
    add_texy_header(${header})
endmacro(tmp_add_header)

add_funcy_header(concept_check.hh HEADER_FILES)
add_funcy_header(concepts.hh HEADER_FILES)
add_header(constant.hh HEADER_FILES)
add_funcy_header(finalize.hh HEADER_FILES)
add_header(fung.hh HEADER_FILES)
add_header(generate.hh HEADER_FILES)
add_header(identity.hh HEADER_FILES)
add_header(linear_algebra.hh HEADER_FILES)
add_header(math.hh HEADER_FILES)
add_funcy_header(operations.hh HEADER_FILES)
add_header(variable.hh HEADER_FILES)

add_header(cmath/arccos.hh HEADER_FILES)
add_header(cmath/arcsine.hh HEADER_FILES)
add_header(cmath/cosine.hh HEADER_FILES)
add_funcy_header(cmath/erf.hh HEADER_FILES)
add_header(cmath/exp.hh HEADER_FILES)
add_header(cmath/log.hh HEADER_FILES)
add_funcy_header(cmath/max.hh HEADER_FILES)
add_funcy_header(cmath/min.hh HEADER_FILES)
add_header(cmath/pow.hh HEADER_FILES)
add_header(cmath/sine.hh HEADER_FILES)
add_header(cmath/tan.hh HEADER_FILES)

add_funcy_header(examples/yield_surface.hh HEADER_FILES)
add_funcy_header(examples/nonlinear_heat.hh HEADER_FILES)
add_funcy_header(examples/volumetric_penalty_functions.hh HEADER_FILES)
add_funcy_header(examples/nonlinear_heat.hh HEADER_FILES)
add_funcy_header(examples/rubber/mooney_rivlin.hh HEADER_FILES)
add_funcy_header(examples/rubber/neo_hooke.hh HEADER_FILES)
add_funcy_header(examples/biomechanics/adipose_tissue_sommer_holzapfel.hh HEADER_FILES)
add_funcy_header(examples/biomechanics/muscle_tissue_martins.hh HEADER_FILES)
add_funcy_header(examples/biomechanics/skin_tissue_hendriks.hh HEADER_FILES)

tmp_add_header(linear_algebra/cofactor.hh HEADER_FILES)
tmp_add_header(linear_algebra/determinant.hh HEADER_FILES)
tmp_add_header(linear_algebra/deviator.hh HEADER_FILES)
tmp_add_header(linear_algebra/deviatoric_invariants.hh HEADER_FILES)
add_funcy_header(linear_algebra/dimension.hh HEADER_FILES)
tmp_add_header(linear_algebra/frobenius_norm.hh HEADER_FILES)
tmp_add_header(linear_algebra/mixed_invariants.hh HEADER_FILES)
tmp_add_header(linear_algebra/principal_invariants.hh HEADER_FILES)
add_funcy_header(linear_algebra/rows_and_cols.hh HEADER_FILES)
tmp_add_header(linear_algebra/strain_tensor.hh HEADER_FILES)
add_funcy_header(linear_algebra/tensor_product.hh HEADER_FILES)
tmp_add_header(linear_algebra/trace.hh HEADER_FILES)
tmp_add_header(linear_algebra/transpose.hh HEADER_FILES)
add_funcy_header(linear_algebra/unit_matrix.hh HEADER_FILES)

tmp_add_header(mathematical_operations/chain.hh HEADER_FILES)
tmp_add_header(mathematical_operations/dot.hh HEADER_FILES)
tmp_add_header(mathematical_operations/product.hh HEADER_FILES)
tmp_add_header(mathematical_operations/scale.hh HEADER_FILES)
tmp_add_header(mathematical_operations/squared.hh HEADER_FILES)
tmp_add_header(mathematical_operations/sum.hh HEADER_FILES)

add_funcy_header(util/add_missing_operators.hh HEADER_FILES)
add_funcy_header(util/add_transposed_matrix.hh HEADER_FILES)
add_funcy_header(util/at.hh HEADER_FILES)
tmp_add_header(util/chainer.hh HEADER_FILES)
add_funcy_header(util/compute_chain.hh HEADER_FILES)
add_funcy_header(util/compute_dot.hh HEADER_FILES)
add_funcy_header(util/compute_product.hh HEADER_FILES)
add_funcy_header(util/compute_sum.hh HEADER_FILES)
add_funcy_header(util/derivative_wrappers.hh HEADER_FILES)
add_funcy_header(util/evaluate_if_present.hh HEADER_FILES)
add_funcy_header(util/exceptions.hh HEADER_FILES)
add_funcy_header(util/extract_rows_and_cols.hh HEADER_FILES)
add_funcy_header(util/indexed_type.hh HEADER_FILES)
add_funcy_header(util/macros.hh HEADER_FILES)
add_funcy_header(util/mathop_traits.hh HEADER_FILES)
add_funcy_header(util/static_checks.hh HEADER_FILES)
add_funcy_header(util/static_checks_nrows_ncols.hh HEADER_FILES)
add_funcy_header(util/third.hh HEADER_FILES)
add_funcy_header(util/traverse.hh HEADER_FILES)
add_funcy_header(util/type_traits.hh HEADER_FILES)
add_funcy_header(util/voider.hh HEADER_FILES)
add_funcy_header(util/zero.hh HEADER_FILES)

add_texy_header(util/string.hh)
add_stringy_header(util/string.hh)
